# Generated by Django 3.1.6 on 2021-02-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='id_liked_tweet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
