# Generated by Django 3.1.6 on 2021-02-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_like_id_liked_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id_liked_tweet',
            field=models.IntegerField(),
        ),
    ]
