# Generated by Django 3.1.6 on 2021-02-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210227_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id_liked_tweet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
