# Generated by Django 3.1.6 on 2021-02-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210227_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id_liked_tweet',
        ),
    ]
