# Generated by Django 3.1.6 on 2021-02-28 19:31

from django.db import migrations
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_like_id_liked_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='datetime',
            field=network.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
